### PR TITLE
Rename conceptually useless files

### PR DESCRIPTION
**Pull request by jcyuan**
changes:

1, rename `CameraManager.cs` to `XPlatformVideoDeviceManager.cs`
2, remove `Camera.cs` and `CameraInfo.cs` because in a system there is actually no camera such device, all are video capture devices.

discussions are welcome.

### CODE REVIEW

**Comment by Speykious** [comment]
I'm not sure I understand the point of this PR. `XPlatformVideoDeviceManager` is a really long and confusing name. What is it even doing? `CameraManager` is much clearer. I'd much prefer to keep the `Camera` terminology as-is.

What do you mean by "because in a system there is actually no camera such device"?

**Comment by jcyuan** [comment]
> 

in a system, Camrea / VirtualCamera / Digital Capture Card / HDMIInput / etc are all VideoCaptureingDevice, there is no a classification only for Camrea, that's why your Camrea.cs / CamreaInfo.cs were just an empty class, because i believe it's meant to be empty, because all the features are in its base class already....

about the `XPlatformVideoDeviceManager` name, it doesn't matter, just rename to whatever you want.
XPlatform means cross platform, just if use X the name will be more short.... :p

**Comment by Speykious** [comment]
Even then, I'd still prefer `Camera`.

One thing I know from FFmpeg is that DShow doesn't make a difference between cameras and screens on Windows, yet I still kept the `Camera` and `Display` classes as separate.

I think it's better to keep these classes for semantic expression of the most common usage. If you know you're interacting with a camera, use `Camera`. If you know you're interacting with a display, use `Display`. Otherwise use `VideoDevice` directly.

**Comment by jcyuan** [comment]
> 

yes i know that, just if i'm working with a HDMI device, and i have to use `Camera` class that makes me feel a little unconfortable 😅 (personally)...
and i can't use `VideoDeviceManager` in this case because this way the code won't be cross platform.
mmm, it's ok, don't worry. just a suggestion.

**Comment by Speykious** [comment]
> > 
> 
> yes i know that, just if i'm working with a HDMI device, and i have to use `Camera` class that makes me feel a little uncomfortable sweat_smile (personally)... and i can't use `VideoDeviceManager` in this case because this way the code won't be cross platform. mmm, it's ok, don't worry. just a suggestion.

I suggest you create your own `HDMIDeviceManager` inheriting from `VideoDeviceManager` and have this kind of code in it:
https://github.com/Speykious/SeeShark/blob/cc4aa3b69053f08c92b77528ab95d326c91d7f72/SeeShark/Device/CameraManager.cs#L18-L28
or even just copy the whole class and rename it, it's probably very similar everywhere and the code is small as you pointed out.

Will work mighty fine and you'll be able to change the input format to something else if it doesn't work for your use-case :p

**Comment by jcyuan** [comment]
> 

👌 yeah, actually the main problem is that there is no way to detect if the device is a HDMI or a Camera etc.... only thing you can know is that it's a video device... 🙄😳..
never mind, i'll just use `VideoManager` and this actually worked fine for me. for cross platform i think i might have a new helper class to do the enumeration things as you suggested. yeah. 👍

**Pull request closed without merging**
